#include "WallpaperApplier.h"
#include "ConfigManager.h"
#include <QProcess>
#include <QFileInfo>
#include <QStringList>
#include <QFile>
#include <QTextStream>
#include <QStandardPaths>
#include <QDir>
#include <QThread>
#include <QImage>
#include <QTransform>
#include <QDebug>

static const QStringList VIDEO_EXTS = {
    "mp4","mkv","avi","webm","mov","gif","flv","wmv"
};

bool WallpaperApplier::isVideoFile(const QString &path)
{
    return VIDEO_EXTS.contains(QFileInfo(path).suffix().toLower());
}

QString WallpaperApplier::fillModeToHyprpaper(FillMode mode)
{
    switch (mode) {
        case FillMode::Cover:   return "cover";
        case FillMode::Contain: return "contain";
        default:                return "cover";
    }
}

// Video fill: 0=Cover(panscan), 1=Contain(keepaspect=yes)
// Video rot:  0=None, 1=90, 2=180, 3=270
static QString mpvOptions(int fillIdx, int rotIdx, bool audio, int volume)
{
    QStringList opts;
    opts << "--loop";
    switch (fillIdx) {
        case 0: opts << "--panscan=1.0";    break;
        case 1: opts << "--keepaspect=yes"; break;
        default: opts << "--panscan=1.0"; break;
    }
    switch (rotIdx) {
        case 0: break;
        case 1: opts << "--video-rotate=90";  break;
        case 2: opts << "--video-rotate=180"; break;
        case 3: opts << "--video-rotate=270"; break;
        default: break;
    }
    if (!audio)
        opts << "--no-audio";
    else
        opts << QString("--volume=%1").arg(volume);
    return opts.join(" ");
}

QString WallpaperApplier::prepareRotatedImage(const QString &src, WallpaperRotation rot)
{
    if (rot == WallpaperRotation::Normal) return QString();
    QImage img(src);
    if (img.isNull()) { qWarning() << "prepareRotatedImage: cannot load" << src; return QString(); }
    QTransform t;
    switch (rot) {
        case WallpaperRotation::Clockwise90:  t.rotate(90);  break;
        case WallpaperRotation::Clockwise180: t.rotate(180); break;
        case WallpaperRotation::Clockwise270: t.rotate(270); break;
        default: break;
    }
    QImage result = img.transformed(t, Qt::SmoothTransformation);
    QString cacheDir = QStandardPaths::writableLocation(QStandardPaths::CacheLocation) + "/HyprWall";
    QDir().mkpath(cacheDir);
    QString tmp = cacheDir + "/" + QFileInfo(src).baseName() + "_rot.png";
    if (!result.save(tmp, "PNG")) { qWarning() << "prepareRotatedImage: save failed" << tmp; return QString(); }
    qDebug() << "Rotated image ->" << tmp;
    return tmp;
}

static void writeHyprpaperConf(const QMap<QString, WallpaperConfig> &all)
{
    QString confDir = QStandardPaths::writableLocation(QStandardPaths::ConfigLocation) + "/hypr";
    QDir().mkpath(confDir);
    QFile f(confDir + "/hyprpaper.conf");
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) return;
    QTextStream ts(&f);
    ts << "# Generated by HyprWall\n\nsplash = false\n\n";
    for (auto it = all.cbegin(); it != all.cend(); ++it) {
        const WallpaperConfig &c = it.value();
        if (c.filePath.isEmpty() || WallpaperApplier::isVideoFile(c.filePath)) continue;
        QString path = c.filePath;
        QString rot = WallpaperApplier::prepareRotatedImage(path, c.rotation);
        if (!rot.isEmpty()) path = rot;
        ts << "wallpaper {\n"
           << "    monitor = " << c.monitorName << "\n"
           << "    path = " << path << "\n"
           << "    fit_mode = " << WallpaperApplier::fillModeToHyprpaper(c.fillMode) << "\n"
           << "}\n\n";
        qDebug() << "[conf] monitor" << c.monitorName << "->" << path;
    }
    f.close();
    qDebug() << "[conf] written to" << (confDir + "/hyprpaper.conf");
}

bool WallpaperApplier::apply(const WallpaperConfig &cfg)
{
    if (cfg.filePath.isEmpty()) { qWarning() << "apply: empty filePath"; return false; }

    if (isVideoFile(cfg.filePath)) {
        stopVideo(cfg.monitorName);
        QString opts = mpvOptions(
            static_cast<int>(cfg.fillMode),
            static_cast<int>(cfg.rotation),
            cfg.audioEnabled, cfg.audioVolume);
        QStringList args;
        args << "-o" << opts << cfg.monitorName << cfg.filePath;
        qDebug() << "mpvpaper" << args;
        return QProcess::startDetached("mpvpaper", args);
    }

    QString path = cfg.filePath;
    QString rotPath = prepareRotatedImage(path, cfg.rotation);
    if (!rotPath.isEmpty()) path = rotPath;
    QString fitMode = fillModeToHyprpaper(cfg.fillMode);

    bool running = false;
    {
        QProcess chk;
        chk.start("pgrep", {"-x", "hyprpaper"});
        chk.waitForFinished(1000);
        running = !chk.readAllStandardOutput().trimmed().isEmpty();
    }

    if (running) {
        QString ipcArg = QString("%1, %2, %3").arg(cfg.monitorName, path, fitMode);
        QProcess p;
        p.start("hyprctl", {"hyprpaper", "wallpaper", ipcArg});
        p.waitForFinished(3000);
        QString out = p.readAllStandardOutput().trimmed();
        qDebug() << "IPC ->" << (out.isEmpty() ? "(empty=ok)" : out);
        if (!out.toLower().contains("error") && !out.toLower().contains("bad"))
            return true;
        qDebug() << "IPC failed, restarting hyprpaper...";
    }

    auto &cm = ConfigManager::instance();
    cm.setConfig(cfg.monitorName, cfg);
    writeHyprpaperConf(cm.configs());
    QProcess::execute("pkill", {"-x", "hyprpaper"});
    QThread::msleep(400);
    bool ok = QProcess::startDetached("hyprpaper", {});
    qDebug() << "hyprpaper restarted:" << ok;
    return ok;
}

void WallpaperApplier::stopVideo(const QString &monitor)
{
    QProcess::execute("pkill", {"-f", QString("mpvpaper.*%1").arg(monitor)});
}

void WallpaperApplier::toggleAudio(const QString &monitor)
{
    auto &cm = ConfigManager::instance();
    cm.load();
    WallpaperConfig cfg = cm.getConfig(monitor);
    cfg.audioEnabled = !cfg.audioEnabled;
    cm.setConfig(monitor, cfg);
    cm.save();
    apply(cfg);
}
